sudo: false
language: python
stages:
    - linting
    - test
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install: travis_retry pip install tox-travis
script: tox --recreate

jobs:
    include:
    - stage: linting
      python: '3.6'
      env:
      install:
      - pip install pre-commit
      - pre-commit install-hooks
      before_script:
      services:
      script:
      - pre-commit run --all-files
